version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - transcendence


volumes:
  pgdata:

networks:
  transcendence:
