version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - transcendence


volumes:
  pgdata:

networks:
  transcendence:
